In [1]:
from sklearn import datasets
from keras.utils import to_categorical
from matplotlib import pyplot as plt
import random
from model import ELM
import numpy as np
from sklearn.model_selection import train_test_split

2022-12-24 11:41:55.796952: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-24 11:41:56.213005: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2022-12-24 11:41:56.213060: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2022-12-24 11:41:56.213064: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nv

In [2]:
# Network Settings
num_classes = 3
num_hidden_layers = 512
input_length = 4

In [3]:
iris = datasets.load_iris()
x = iris.data
y = iris.target

In [4]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, stratify=y)

y_train = to_categorical(y_train, num_classes).astype(np.float32)
y_test = to_categorical(y_test, num_classes).astype(np.float32)

In [7]:
x_train.shape

(105, 4)

In [8]:
y_train.shape

(105, 3)

In [9]:
x_test.shape

(45, 4)

In [10]:
y_test.shape

(45, 3)

In [11]:
# create instance of our model
model = ELM(
    input_length,
    num_hidden_layers,
    num_classes
)

Input length/nodes:  4
Number of hidden layers:  512
Number output units/classes:  3
Bias shape: (512,)
W shape: (4, 512)
Beta shape: (512, 3)


In [12]:
# Train
model.fit(x_train, y_train, display_time=True)
train_loss, train_acc = model.evaluate(x_train, y_train)
print('train loss: %f' % train_loss)
print('train acc: %f' % train_acc)

# likely having issues with overfitting here since it's 0% loss and 100% accuracy...

Training time (seconds): 0.036978960037231445
train loss: 0.000000
train acc: 1.000000


In [13]:
# Predictions
predictions = model(x_test)

In [14]:
correct_count = 0
for idx, val in enumerate(x_test):
    print(y_test[idx])
    print(f'Actual {np.argmax(y_test[idx])}')
    print(f'Predicted {np.argmax(predictions[idx])}')
    print(f'With prob: {str(round(np.max(predictions[idx]), 2))}')
    if (np.argmax(y_test[idx]) == np.argmax(predictions[idx])):
        correct_count = correct_count + 1
    print("------------------")

print(f'Total testing accuracy: {round(correct_count / len(x_test), 2)}')

[1. 0. 0.]
Actual 0
Predicted 0
With prob: 1.0
------------------
[0. 1. 0.]
Actual 1
Predicted 1
With prob: 0.94
------------------
[0. 0. 1.]
Actual 2
Predicted 1
With prob: 0.78
------------------
[0. 0. 1.]
Actual 2
Predicted 2
With prob: 0.86
------------------
[0. 0. 1.]
Actual 2
Predicted 2
With prob: 5.27
------------------
[0. 1. 0.]
Actual 1
Predicted 1
With prob: 1.03
------------------
[0. 0. 1.]
Actual 2
Predicted 2
With prob: 2.06
------------------
[0. 1. 0.]
Actual 1
Predicted 1
With prob: 1.84
------------------
[0. 1. 0.]
Actual 1
Predicted 1
With prob: 1.03
------------------
[0. 0. 1.]
Actual 2
Predicted 2
With prob: 0.83
------------------
[1. 0. 0.]
Actual 0
Predicted 0
With prob: 1.0
------------------
[1. 0. 0.]
Actual 0
Predicted 0
With prob: 1.0
------------------
[1. 0. 0.]
Actual 0
Predicted 0
With prob: 1.02
------------------
[0. 0. 1.]
Actual 2
Predicted 2
With prob: 0.92
------------------
[1. 0. 0.]
Actual 0
Predicted 2
With prob: 1.97
-----------------