In [92]:
from sklearn import datasets
from keras.utils import to_categorical
from matplotlib import pyplot as plt
import random
from model import ELM
import numpy as np
from sklearn.model_selection import train_test_split

In [93]:
# set this to enforce a seed for randomness for reproducibility
np.random.seed(0)

In [94]:
# Network Settings
num_classes = 3
num_hidden_layers = 512
input_length = 4

In [95]:
iris = datasets.load_iris()
x = iris.data
y = iris.target

In [96]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [97]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [98]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, stratify=y)

y_train = to_categorical(y_train, num_classes).astype(np.float32)
y_test = to_categorical(y_test, num_classes).astype(np.float32)

In [99]:
x_train.shape

(105, 4)

In [100]:
y_train.shape

(105, 3)

In [101]:
x_test.shape

(45, 4)

In [102]:
y_test.shape

(45, 3)

In [103]:
# create instance of our model
model = ELM(
    input_length,
    num_hidden_layers,
    num_classes
)

Input length/nodes:  4
Number of hidden layers:  512
Number output units/classes:  3
Bias shape: (512,)
W shape: (4, 512)
Beta shape: (512, 3)


In [104]:
# Train
model.fit(x_train, y_train, display_time=True)
train_loss, train_acc = model.evaluate(x_train, y_train)
print('train loss: %f' % train_loss)
print('train acc: %f' % train_acc)

# likely having issues with overfitting here since it's 0% loss and 100% accuracy...

Training time (seconds): 0.011989116668701172
train loss: 0.000000
train acc: 1.000000


In [105]:
# Predictions
predictions = model(x_test)

In [106]:
correct_count = 0
for idx, val in enumerate(x_test):
    print(y_test[idx])
    print(f'Actual {np.argmax(y_test[idx])}')
    print(f'Predicted {np.argmax(predictions[idx])}')
    print(f'With prob: {str(round(np.max(predictions[idx]), 2))}')
    if (np.argmax(y_test[idx]) == np.argmax(predictions[idx])):
        correct_count = correct_count + 1
    print("------------------")

print(f'Total testing accuracy: {round(correct_count / len(x_test), 2)}')

[0. 0. 1.]
Actual 2
Predicted 2
With prob: 1.32
------------------
[0. 0. 1.]
Actual 2
Predicted 2
With prob: 1.0
------------------
[1. 0. 0.]
Actual 0
Predicted 0
With prob: 1.0
------------------
[1. 0. 0.]
Actual 0
Predicted 1
With prob: 1.76
------------------
[0. 1. 0.]
Actual 1
Predicted 2
With prob: 0.84
------------------
[1. 0. 0.]
Actual 0
Predicted 0
With prob: 0.98
------------------
[0. 1. 0.]
Actual 1
Predicted 1
With prob: 1.14
------------------
[0. 0. 1.]
Actual 2
Predicted 2
With prob: 1.47
------------------
[1. 0. 0.]
Actual 0
Predicted 0
With prob: 0.98
------------------
[0. 1. 0.]
Actual 1
Predicted 1
With prob: 1.55
------------------
[1. 0. 0.]
Actual 0
Predicted 0
With prob: 1.01
------------------
[0. 0. 1.]
Actual 2
Predicted 2
With prob: 0.94
------------------
[1. 0. 0.]
Actual 0
Predicted 0
With prob: 1.0
------------------
[0. 0. 1.]
Actual 2
Predicted 2
With prob: 1.18
------------------
[0. 1. 0.]
Actual 1
Predicted 1
With prob: 1.26
-----------------